// User
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const CLEAR_USER_REDUCER = 'CLEAR_USER_REDUCER';

// Room
export const ROOMS_LOADING = 'ROOMS_LOADING';
export const ROOMS_LOADED = 'ROOMS_LOADED';
export const ROOMS_LOADED_FAIL = 'ROOMS_LOADED_FAIL';
export const SET_ROOM_ID = 'SET_ROOM_ID';
export const CLEAR_CURRENT_ROOM_ID = 'CLEAR_CURRENT_ROOM_ID';
export const JOIN_ROOM = 'JOIN_ROOM';
export const JOIN_ROOM_FAIL = 'JOIN_ROOM_FAIL';
export const CREATE_ROOM = 'CREATE_ROOM';
export const CREATE_ROOM_FAIL = 'CREATE_ROOM_FAIL';
export const CLEAR_ROOM_REDUCER = 'CLEAR_ROOM_REDUCER';

// Channel
export const CHANNELS_LOADING = 'CHANNELS_LOADING';
export const CHANNELS_LOADED = 'CHANNELS_LOADED';
export const CHANNELS_LOADED_FAIL = 'CHANNELS_LOADED_FAIL';
export const SET_CHANNEL_ID = 'SET_CHANNEL_ID';
export const CLEAR_CURRENT_CHANNEL_ID = 'CLEAR_CURRENT_CHANNEL_ID';
export const CREATE_CHANNEL = 'CREATE_CHANNEL';
export const CREATE_CHANNEL_FAIL = 'CREATE_CHANNEL_FAIL';
export const DELETE_CHANNEL = 'DELETE_CHANNEL';
export const DELETE_CHANNEL_FAIL = 'DELETE_CHANNEL_FAIL';
export const CLEAR_CHANNEL_REDUCER = 'CLEAR_CHANNEL_REDUCER';

// Member
export const MEMBERS_LOADING = 'MEMBERS_LOADING';
export const MEMBERS_LOADED = 'MEMBERS_LOADED';
export const MEMBERS_LOADED_FAIL = 'MEMBERS_LOADED_FAIL';
export const CREATE_MEMBER = 'CREATE_MEMBER';
export const CREATE_MEMBER_FAIL = 'CREATE_MEMBER_FAIL';
export const CLEAR_MEMBER_REDUCER = 'CLEAR_MEMBER_REDUCER';

// Message
export const MESSAGES_LOADING = 'MESSAGES_LOADING';
export const MESSAGES_LOADED = 'MESSAGES_LOADED';
export const MESSAGES_LOADED_FAIL = 'MESSAGES_LOADED_FAIL';
export const SET_MESSAGE = 'SET_MESSAGE';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const SEND_MESSAGE_FAIL = 'SEND_MESSAGE_FAIL';
export const CLEAR_MESSAGE_REDUCER = 'CLEAR_MESSAGE_REDUCER';
