// User
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

// Room
export const ROOMS_LOADING = 'ROOMS_LOADING';
export const ROOMS_LOADED = 'ROOMS_LOADED';
export const ROOMS_LOADED_FAIL = 'ROOMS_LOADED_FAIL';
export const SET_ROOM_ID = 'SET_ROOM_ID';

// Channel
export const CHANNELS_LOADING = 'CHANNELS_LOADING';
export const CHANNELS_LOADED = 'CHANNELS_LOADED';
export const CHANNELS_LOADED_FAIL = 'CHANNELS_LOADED_FAIL';
export const SET_CHANNEL_ID = 'SET_CHANNEL_ID';

// Member
export const MEMBER_LOADING = 'MEMBER_LOADING';
export const MEMBER_LOADED = 'MEMBER_LOADED';
export const MEMBER_LOADED_FAIL = 'MEMBER_LOADED_FAIL';

// Message
export const MESSAGES_LOADING = 'MESSAGES_LOADING';
export const MESSAGES_LOADED = 'MESSAGES_LOADED';
export const MESSAGES_LOADED_FAIL = 'MESSAGES_LOADED_FAIL';
export const SET_MESSAGE = 'SET_MESSAGE';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const SEND_MESSAGE_FAIL = 'SEND_MESSAGE_FAIL';
